
- name: disable the default nodejs
  ansible.builtin.shell: dnf module disable nodejs -y

- name: enabling the nodejs:20
  ansible.builtin.shell: dnf module enable nodejs:20 -y

- name: Installing nodejs
  ansible.builtin.package:
   name: nodejs
   state: present

- name: Downloading the {{ component }} code
  ansible.builtin.get_url:
   url: "{{ code }}"
   dest: "{{ tmp_folder }}"

- name: creating a {{ app_user }}
  ansible.builtin.user:
   name: "{{ app_user }}"


- name: deleting the application directory
  ansible.builtin.file:
   name: "{{ app_dir }}"
   state: absent


- name: creating the directory
  ansible.builtin.file:
   name: "{{ app_dir }}"
   state: directory

- name: Extracting the {{ component }} code
  ansible.builtin.unarchive:
   src: "{{ tmp_folder }}"
   dest: "{{ app_dir }}"
   remote_src: yes

- name: Instaling the {{ component }} artifacts
  ansible.builtin.npm:
   path: "{{ app_dir }}"

- name: copying systemd service
  ansible.builtin.template:
   src: user.service
   dest: "{{ system_path }}"

- name: deamon reload
  ansible.builtin.systemd_service:
   daemon_reload: yes

- name: restart and enable {{ component }}
  ansible.builtin.service:
   name: "{{ component }}"
   state: restarted
   enabled: yes
