
- name: disable the default nodejs
  ansible.builtin.shell: dnf module disable nodejs -y

- name: enabling the nodejs:20
  ansible.builtin.shell: dnf module enable nodejs:20 -y

- name: Installing nodejs
  ansible.builtin.package:
   name: nodejs
   state: present

- name: app setup
  include_role:
   name: common
   tasks_from: app-setup.yaml

- name: Instaling the {{ component }} artifacts
  ansible.builtin.npm:
   path: "{{ app_dir }}"

- name: copying systemd service
  ansible.builtin.template:
   src: user.service
   dest: "{{ system_path }}"

- name: deamon reload
  ansible.builtin.systemd_service:
   daemon_reload: yes

- name: restart and enable {{ component }}
  ansible.builtin.service:
   name: "{{ component }}"
   state: restarted
   enabled: yes
