- name: installing the items
  ansible.builtin.package:
   name: "{{ item }}"
   state: present
  loop:
   - python3
   - gcc
   - python3-devel

- name: Downloading the {{ component }} code
  ansible.builtin.get_url:
   url: "{{ code }}"
   dest: "{{ tmp_folder }}"

- name: creating a {{ app_user }}
  ansible.builtin.user:
   name: "{{ app_user }}"


- name: deleting the application directory
  ansible.builtin.file:
   name: "{{ app_dir }}"
   state: absent


- name: creating the directory
  ansible.builtin.file:
   name: "{{ app_dir }}"
   state: directory

- name: Extracting the {{ component }} code
  ansible.builtin.unarchive:
   src: "{{ tmp_folder }}"
   dest: "{{ app_dir }}"
   remote_src: yes

- name: installing the dependencies
  ansible.builtin.shell: pip3 install -r requirements.txt
  args:
   chdir: "{{ app_dir }}"

- name: setting up the system
  ansible.builtin.template:
   src: payment.service
   dest: "{{ system_path }}"

- name: deamon reload
  ansible.builtin.systemd_service:
    daemon_reload: yes

- name: restart and enable {{ component }}
  ansible.builtin.service:
   name: "{{ component }}"
   state: restarted
   enabled: yes