
- name: disable default nginx
  ansible.builtin.shell: dnf module disable nginx -y

- name: enable 1.24 version nginx
  ansible.builtin.shell: dnf module enable nginx:1.24 -y

- name: installing the nginx
  ansible.builtin.package:
   name: nginx
   state: present

- name: start and enable nginx
  ansible.builtin.service:
   name: nginx
   state: started
   enabled: yes

-  name: download frontend code
   ansible.builtin.get_url:
      url: "{{ code }}"
      dest: "{{ tmp_folder }}"

-  name: remove html directory
   ansible.builtin.file:
      path: "{{ html_dir }}"
      state: absent

-  name: create html directory
   ansible.builtin.file:
      path: "{{ html_dir }}"
      state: directory

- name: extracting frontend code
  ansible.builtin.unarchive:
   src: "{{ tmp_folder }}"
   dest: "{{ html_dir }}"
   remote_src: yes

- name: setting up nginx configuration
  ansible.builtin.template:
   src: nginx.conf
   dest: /etc/nginx/nginx.conf
   notify:
    - restart nginx
   

