
- name: disable the default nodejs
  ansible.builtin.shell: dnf module disable nodejs -y

- name: enabling the nodejs:20
  ansible.builtin.shell: dnf module enable nodejs:20 -y

- name: Installing nodejs
  ansible.builtin.package:
   name: nodejs
   state: present

- name: app setup
  include_role:
    name: app-setup
    task_from: common

- name: Instaling the {{ component }} artifacts
  ansible.builtin.npm:
   path: "{{ app_dir }}"

- name: copying systemd service
  ansible.builtin.template:
   src: catalogue.service
   dest: "{{ system_path }}"

- name: systemctl deamon reload
  ansible.builtin.systemd_service:
    daemon_reload: true

- name: Starting and enabling {{ component }}
  ansible.builtin.service:
   name: "{{ component }}"
   state: started
   enabled: yes

- name: copying the mongod repo file
  ansible.builtin.template:
   src: mongod.repo
   dest: /etc/yum.repos.d/mongo.repo

- name: Installing mongod
  ansible.builtin.package:
   name: mongodb-mongosh
   state: present

- name: load products
  ansible.builtin.shell: mongosh --host mongodb.{{ env }}.clouddevops.life < /app/db/master-data.js





